### ISSUE TITLE
todo: update literature data [web module]

### ISSUE THREAD

**Issue by celinesin** [menchelab/Analytics_Module#11]
- [x] merge tables in sql db so publication date is not NULL
- [ ] implement way to display this from dataswimmer

Later:
- [ ] write script to auto update database (see felix instructions below)
