### ISSUE TITLE
todo: refine interface for dataswimmer

### ISSUE THREAD

**Issue by celinesin** [menchelab/Analytics_Module#13]
**Make it prettier**
- [x] talk to jörg to find out what's good/bad
- [ ] change fonts to something pretty (esp in pull down menus)
- [ ] match colors with dataDiVR
- [ ] remove stupidly named entries (dumb bunny, etc)
- [ ] consistent case for different annotation sets (molecular_function, biological_process, DISEASE, etc…)

**Make it more usable**
- [ ] tooltips everywhere
- [ ] more words to supplement icons
- [ ] more words in general

**Add functionality**
- [ ] implement inspection panel (issue #8, #9, #12)
