### ISSUE TITLE
todo: shopping carts

### ISSUE THREAD

**Issue by celinesin** [menchelab/Analytics_Module#5]
- [ ] add logic for if shopping cart is empty

logic for if shopping cart is empty: maybe move all genes there
maybe a pop up to offer moving them
streamline "moving menu"

- [ ] implement multiple shopping carts
(and then maybe functions that you can merge intersect etc)

- [ ] implement add/remove things from shopping carts

- [ ] ? what other awesome stuff?
