### ISSUE TITLE
todo: selection lists

### ISSUE THREAD

**Issue by celinesin** [menchelab/Analytics_Module#7]
- [x] implement button to delete selection lists from database
- [ ] make it intuitive to move objects from selection list to shopping cart
- [ ] clean up stupid selection lists
